IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DIA_JangadItem' AND COLUMN_NAME = 'ItemFilePath')
BEGIN
   ALTER TABLE DIA_JangadItem ADD ItemFilePath nvarchar(500) NULL
END