//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class DB_A157D8_AnjaliMISEntities1 : DbContext
    {
        public DB_A157D8_AnjaliMISEntities1()
            : base("name=DB_A157D8_AnjaliMISEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACC_AccountHead> ACC_AccountHead { get; set; }
        public DbSet<ACC_Bank> ACC_Bank { get; set; }
        public DbSet<ACC_Expense> ACC_Expense { get; set; }
        public DbSet<ACC_ExpenseHistory> ACC_ExpenseHistory { get; set; }
        public DbSet<ACC_PaymentMode> ACC_PaymentMode { get; set; }
        public DbSet<ACC_Receipt> ACC_Receipt { get; set; }
        public DbSet<ACC_ReceiptHistory> ACC_ReceiptHistory { get; set; }
        public DbSet<ACC_Tax> ACC_Tax { get; set; }
        public DbSet<DIA_AssignCassettToMachine> DIA_AssignCassettToMachine { get; set; }
        public DbSet<DIA_Cassett> DIA_Cassett { get; set; }
        public DbSet<DIA_Jangad> DIA_Jangad { get; set; }
        public DbSet<DIA_JangadHistory> DIA_JangadHistory { get; set; }
        public DbSet<DIA_JangadItem> DIA_JangadItem { get; set; }
        public DbSet<DIA_Machine> DIA_Machine { get; set; }
        public DbSet<DIA_MachineMaintenance> DIA_MachineMaintenance { get; set; }
        public DbSet<DIA_MachineWorkHistory> DIA_MachineWorkHistory { get; set; }
        public DbSet<EMP_Department> EMP_Department { get; set; }
        public DbSet<EMP_Designation> EMP_Designation { get; set; }
        public DbSet<EMP_Employee> EMP_Employee { get; set; }
        public DbSet<EMP_EmployeeAttendance> EMP_EmployeeAttendance { get; set; }
        public DbSet<EMP_Punch> EMP_Punch { get; set; }
        public DbSet<INV_Category> INV_Category { get; set; }
        public DbSet<INV_Invoice> INV_Invoice { get; set; }
        public DbSet<INV_InvoiceHistory> INV_InvoiceHistory { get; set; }
        public DbSet<INV_InvoiceItem> INV_InvoiceItem { get; set; }
        public DbSet<INV_Item> INV_Item { get; set; }
        public DbSet<INV_ItemConfiguration> INV_ItemConfiguration { get; set; }
        public DbSet<INV_ItemPrice> INV_ItemPrice { get; set; }
        public DbSet<INV_PurchaseOrder> INV_PurchaseOrder { get; set; }
        public DbSet<INV_PurchaseOrderHistory> INV_PurchaseOrderHistory { get; set; }
        public DbSet<INV_PurchaseOrderItem> INV_PurchaseOrderItem { get; set; }
        public DbSet<INV_StockHistory> INV_StockHistory { get; set; }
        public DbSet<INV_Unit> INV_Unit { get; set; }
        public DbSet<LOC_City> LOC_City { get; set; }
        public DbSet<LOC_Country> LOC_Country { get; set; }
        public DbSet<LOC_State> LOC_State { get; set; }
        public DbSet<LOG_DBMSError> LOG_DBMSError { get; set; }
        public DbSet<LOG_PageError> LOG_PageError { get; set; }
        public DbSet<LOG_PageVisited> LOG_PageVisited { get; set; }
        public DbSet<LOG_SPExecution> LOG_SPExecution { get; set; }
        public DbSet<MST_Party> MST_Party { get; set; }
        public DbSet<SEC_LoginHistory> SEC_LoginHistory { get; set; }
        public DbSet<SEC_User> SEC_User { get; set; }
        public DbSet<SEC_UserPrivileges> SEC_UserPrivileges { get; set; }
        public DbSet<SYS_Company> SYS_Company { get; set; }
        public DbSet<SYS_FinYear> SYS_FinYear { get; set; }
        public DbSet<SYS_Module> SYS_Module { get; set; }
        public DbSet<SYS_OperationType> SYS_OperationType { get; set; }
        public DbSet<SYS_PartyType> SYS_PartyType { get; set; }
        public DbSet<SYS_PolishingStage> SYS_PolishingStage { get; set; }
        public DbSet<SYS_Status> SYS_Status { get; set; }
        public DbSet<SQL_CustomFK> SQL_CustomFK { get; set; }
        public DbSet<SQL_FixColumn> SQL_FixColumn { get; set; }
        public DbSet<SQL_FKDisplayMember> SQL_FKDisplayMember { get; set; }
        public DbSet<SQL_Sequence> SQL_Sequence { get; set; }
    
        public virtual ObjectResult<PR_SEC_UserPrivileges_SelectByUserID_Result1> PR_SEC_UserPrivileges_SelectByUserID(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_SEC_UserPrivileges_SelectByUserID_Result1>("PR_SEC_UserPrivileges_SelectByUserID", userIDParameter);
        }
    }
}
