//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA_JangadItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIA_JangadItem()
        {
            this.DIA_MachineWorkHistory = new HashSet<DIA_MachineWorkHistory>();
        }
    
        public int JangadItemID { get; set; }
        public int JangadID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Dia { get; set; }
        public Nullable<decimal> PavalionAngle { get; set; }
        public Nullable<decimal> CrownAngle { get; set; }
        public Nullable<decimal> CrownHeight { get; set; }
        public Nullable<decimal> Girdle { get; set; }
        public Nullable<decimal> Para1 { get; set; }
        public Nullable<decimal> Para2 { get; set; }
        public Nullable<decimal> Para3 { get; set; }
        public Nullable<int> CassettsID { get; set; }
        public int PolishingStageID { get; set; }
        public string PavalionORCrown { get; set; }
        public int UserID { get; set; }
        public int StatusID { get; set; }
        public string QCRemarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> PhysicalReceived { get; set; }
        public Nullable<System.DateTime> PhysicalReceivedDateTime { get; set; }
        public Nullable<bool> PhysicalSend { get; set; }
        public Nullable<System.DateTime> PhysicalSendDateTime { get; set; }
        public Nullable<bool> Delivered { get; set; }
        public Nullable<System.DateTime> DeliveredDateTime { get; set; }
        public Nullable<decimal> RWeight { get; set; }
        public Nullable<decimal> PWeight { get; set; }
        public Nullable<decimal> Culet { get; set; }
        public string JangadItemCode { get; set; }
    
        public virtual DIA_Cassett DIA_Cassett { get; set; }
        public virtual DIA_Jangad DIA_Jangad { get; set; }
        public virtual SYS_PolishingStage SYS_PolishingStage { get; set; }
        public virtual SYS_Status SYS_Status { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIA_MachineWorkHistory> DIA_MachineWorkHistory { get; set; }
    }
}
