//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIA_JangadHistory
    {
        public int JangadHistoryID { get; set; }
        public int CompanyID { get; set; }
        public int PartyID { get; set; }
        public int Quantity { get; set; }
        public decimal Weight { get; set; }
        public int StatusID { get; set; }
        public int UserID { get; set; }
        public int Amount { get; set; }
        public Nullable<int> RecivedAmount { get; set; }
        public Nullable<int> PendingAmount { get; set; }
        public int JangadNo { get; set; }
        public System.DateTime Created { get; set; }
        public string Remarks { get; set; }
        public decimal PricePerCarat { get; set; }
        public int FinYearID { get; set; }
        public Nullable<decimal> CGSTAmount { get; set; }
        public Nullable<decimal> SGSTAmount { get; set; }
        public Nullable<decimal> IGSTAmount { get; set; }
        public Nullable<decimal> TDSAmount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CGST { get; set; }
        public Nullable<int> SGST { get; set; }
        public Nullable<int> IGST { get; set; }
        public Nullable<int> TDS { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public Nullable<decimal> Casar { get; set; }
        public decimal TotalAmount { get; set; }
        public string Operation { get; set; }
        public Nullable<int> JangadID { get; set; }
        public string JangadCode { get; set; }
        public Nullable<int> QTYByThan { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsRatePerThan { get; set; }
        public Nullable<bool> IsRatePerCarat { get; set; }
    
        public virtual ACC_Tax ACC_Tax { get; set; }
        public virtual ACC_Tax ACC_Tax1 { get; set; }
        public virtual ACC_Tax ACC_Tax2 { get; set; }
        public virtual ACC_Tax ACC_Tax3 { get; set; }
        public virtual DIA_Jangad DIA_Jangad { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
        public virtual SYS_FinYear SYS_FinYear { get; set; }
        public virtual MST_Party MST_Party { get; set; }
        public virtual SYS_Status SYS_Status { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
