//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Employee
    {
        public EMP_Employee()
        {
            this.EMP_EmployeeAttendance = new HashSet<EMP_EmployeeAttendance>();
            this.EMP_Punch = new HashSet<EMP_Punch>();
            this.SEC_User1 = new HashSet<SEC_User>();
        }
    
        public int EmployeeID { get; set; }
        public int UserID { get; set; }
        public int CompanyID { get; set; }
        public string EmployeeName { get; set; }
        public int DesignationID { get; set; }
        public string Address { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string IDProofDocName { get; set; }
        public Nullable<int> IDProofNumber { get; set; }
        public string IDProofPhotoPath { get; set; }
        public string PhotoPath { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public int Age { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public int FinYearID { get; set; }
        public string PanNo { get; set; }
        public string AadharNo { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> BankID { get; set; }
        public string IFSCCode { get; set; }
    
        public virtual ACC_Bank ACC_Bank { get; set; }
        public virtual EMP_Department EMP_Department { get; set; }
        public virtual EMP_Designation EMP_Designation { get; set; }
        public virtual LOC_City LOC_City { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
        public virtual SYS_FinYear SYS_FinYear { get; set; }
        public virtual LOC_State LOC_State { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<EMP_EmployeeAttendance> EMP_EmployeeAttendance { get; set; }
        public virtual ICollection<EMP_Punch> EMP_Punch { get; set; }
        public virtual ICollection<SEC_User> SEC_User1 { get; set; }
    }
}
