//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_Item
    {
        public INV_Item()
        {
            this.DIA_MachineMaintenance = new HashSet<DIA_MachineMaintenance>();
            this.INV_InvoiceItem = new HashSet<INV_InvoiceItem>();
            this.INV_ItemConfiguration = new HashSet<INV_ItemConfiguration>();
            this.INV_ItemConfiguration1 = new HashSet<INV_ItemConfiguration>();
            this.INV_ItemPrice = new HashSet<INV_ItemPrice>();
            this.INV_PurchaseOrderItem = new HashSet<INV_PurchaseOrderItem>();
            this.INV_StockHistory = new HashSet<INV_StockHistory>();
        }
    
        public int ItemID { get; set; }
        public int CompanyID { get; set; }
        public string ItemName { get; set; }
        public int UnitID { get; set; }
        public int UserID { get; set; }
        public bool IsConfigurable { get; set; }
        public int Quantity { get; set; }
        public int MinStockLimit { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RejectedQuantity { get; set; }
        public bool IsLock { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<DIA_MachineMaintenance> DIA_MachineMaintenance { get; set; }
        public virtual INV_Category INV_Category { get; set; }
        public virtual ICollection<INV_InvoiceItem> INV_InvoiceItem { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
        public virtual INV_Unit INV_Unit { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<INV_ItemConfiguration> INV_ItemConfiguration { get; set; }
        public virtual ICollection<INV_ItemConfiguration> INV_ItemConfiguration1 { get; set; }
        public virtual ICollection<INV_ItemPrice> INV_ItemPrice { get; set; }
        public virtual ICollection<INV_PurchaseOrderItem> INV_PurchaseOrderItem { get; set; }
        public virtual ICollection<INV_StockHistory> INV_StockHistory { get; set; }
    }
}
