//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_Unit
    {
        public INV_Unit()
        {
            this.INV_Item = new HashSet<INV_Item>();
        }
    
        public int UnitID { get; set; }
        public int UserID { get; set; }
        public string Unit { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual ICollection<INV_Item> INV_Item { get; set; }
    }
}
