//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_IssueReturn
    {
        public int IssueReturnID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> IssueReturnByUserID { get; set; }
        public Nullable<int> IssueReturnToUserID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> IssueReturnDate { get; set; }
        public string IssueReturnNo { get; set; }
        public int FinYearID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ReturnIssueNo { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
        public virtual SEC_User SEC_User1 { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
        public virtual SYS_FinYear SYS_FinYear { get; set; }
    }
}
