//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_ItemConfiguration
    {
        public int ItemConfigurationID { get; set; }
        public int MainItemID { get; set; }
        public int SubItemID { get; set; }
        public int Qunatity { get; set; }
        public int UserID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
    
        public virtual INV_Item INV_Item { get; set; }
        public virtual INV_Item INV_Item1 { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public List<INV_ItemConfiguration> INV_Items { get; set; }
        public bool RetrieveType { get; set; }
    }
}
