//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOC_State
    {
        public LOC_State()
        {
            this.EMP_Employee = new HashSet<EMP_Employee>();
            this.LOC_City = new HashSet<LOC_City>();
            this.MST_Party = new HashSet<MST_Party>();
        }
    
        public int StateID { get; set; }
        public int CountryID { get; set; }
        public string StateName { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<EMP_Employee> EMP_Employee { get; set; }
        public virtual ICollection<LOC_City> LOC_City { get; set; }
        public virtual LOC_Country LOC_Country { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<MST_Party> MST_Party { get; set; }
    }
}
