//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOC_Country
    {
        public LOC_Country()
        {
            this.LOC_State = new HashSet<LOC_State>();
            this.MST_Party = new HashSet<MST_Party>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<LOC_State> LOC_State { get; set; }
        public virtual ICollection<MST_Party> MST_Party { get; set; }
    }
}
