//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOC_City
    {
        public LOC_City()
        {
            this.EMP_Employee = new HashSet<EMP_Employee>();
            this.MST_Party = new HashSet<MST_Party>();
            this.SYS_Company = new HashSet<SYS_Company>();
        }
    
        public int CityID { get; set; }
        public int StateID { get; set; }
        public string CityName { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<EMP_Employee> EMP_Employee { get; set; }
        public virtual LOC_State LOC_State { get; set; }
        public virtual SEC_User SEC_User { get; set; }
        public virtual ICollection<MST_Party> MST_Party { get; set; }
        public virtual ICollection<SYS_Company> SYS_Company { get; set; }
    }
}
