//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_DBMSError
    {
        public int DBMSErrorID { get; set; }
        public string SPDetail { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorProcedure { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string VerifiedRemarks { get; set; }
        public bool IsSolved { get; set; }
    }
}
