//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_PageError
    {
        public int PageErrorID { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorPage { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string SessionID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public string VerifiedRemarks { get; set; }
        public bool IsSolved { get; set; }
    }
}
