//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MST_Party()
        {
            this.DIA_Jangad = new HashSet<DIA_Jangad>();
            this.DIA_JangadHistory = new HashSet<DIA_JangadHistory>();
            this.INV_Invoice = new HashSet<INV_Invoice>();
            this.INV_InvoiceHistory = new HashSet<INV_InvoiceHistory>();
            this.INV_PurchaseOrder = new HashSet<INV_PurchaseOrder>();
            this.INV_PurchaseOrderHistory = new HashSet<INV_PurchaseOrderHistory>();
        }
    
        public int PartyID { get; set; }
        public string PartyName { get; set; }
        public string Address { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int PartyTypeID { get; set; }
        public int CompanyID { get; set; }
        public int UserID { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modofied { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string PanNo { get; set; }
        public string TanNo { get; set; }
        public string AadharNo { get; set; }
        public string GSTIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIA_Jangad> DIA_Jangad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIA_JangadHistory> DIA_JangadHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_Invoice> INV_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_InvoiceHistory> INV_InvoiceHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PurchaseOrder> INV_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PurchaseOrderHistory> INV_PurchaseOrderHistory { get; set; }
        public virtual LOC_City LOC_City { get; set; }
        public virtual LOC_Country LOC_Country { get; set; }
        public virtual LOC_State LOC_State { get; set; }
        public virtual SYS_Company SYS_Company { get; set; }
        public virtual SYS_PartyType SYS_PartyType { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
