//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_UserPrivileges
    {
        public int UserPrivilegesID { get; set; }
        public int ModuleID { get; set; }
        public int UserID { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<System.DateTime> Remarks { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
        public virtual SEC_User SEC_User1 { get; set; }
        public virtual SYS_Module SYS_Module { get; set; }
    }
}
