//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_LoginHistory
    {
        public int LoginHistoryID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogoutTime { get; set; }
        public System.DateTime Created { get; set; }
        public string Remarls { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual SEC_User SEC_User { get; set; }
    }
}
