//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQL_CustomFK
    {
        public Nullable<bool> IsEnable { get; set; }
        public string FKType { get; set; }
        public string TableID { get; set; }
        public Nullable<int> JoinOrder { get; set; }
        public string PKTable { get; set; }
        public string PKSchema { get; set; }
        public string PKColumn { get; set; }
        public string FKTable { get; set; }
        public string FKSchema { get; set; }
        public string FKColumn { get; set; }
        public string CustomFKName { get; set; }
    }
}
