//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Module
    {
        public SYS_Module()
        {
            this.SEC_UserPrivileges = new HashSet<SEC_UserPrivileges>();
        }
    
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string Description { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string URL { get; set; }
        public string IconName { get; set; }
        public bool StrictlyStop { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
        public int Sequence { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<SEC_UserPrivileges> SEC_UserPrivileges { get; set; }
    }
}
