//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Status
    {
        public SYS_Status()
        {
            this.DIA_AssignCassettToMachine = new HashSet<DIA_AssignCassettToMachine>();
            this.DIA_Cassett = new HashSet<DIA_Cassett>();
            this.DIA_Jangad = new HashSet<DIA_Jangad>();
            this.DIA_JangadHistory = new HashSet<DIA_JangadHistory>();
            this.DIA_JangadItem = new HashSet<DIA_JangadItem>();
            this.INV_Invoice = new HashSet<INV_Invoice>();
            this.INV_InvoiceHistory = new HashSet<INV_InvoiceHistory>();
            this.INV_PurchaseOrder = new HashSet<INV_PurchaseOrder>();
            this.INV_PurchaseOrderHistory = new HashSet<INV_PurchaseOrderHistory>();
        }
    
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<DIA_AssignCassettToMachine> DIA_AssignCassettToMachine { get; set; }
        public virtual ICollection<DIA_Cassett> DIA_Cassett { get; set; }
        public virtual ICollection<DIA_Jangad> DIA_Jangad { get; set; }
        public virtual ICollection<DIA_JangadHistory> DIA_JangadHistory { get; set; }
        public virtual ICollection<DIA_JangadItem> DIA_JangadItem { get; set; }
        public virtual ICollection<INV_Invoice> INV_Invoice { get; set; }
        public virtual ICollection<INV_InvoiceHistory> INV_InvoiceHistory { get; set; }
        public virtual ICollection<INV_PurchaseOrder> INV_PurchaseOrder { get; set; }
        public virtual ICollection<INV_PurchaseOrderHistory> INV_PurchaseOrderHistory { get; set; }
    }
}
