//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PartyType
    {
        public SYS_PartyType()
        {
            this.MST_Party = new HashSet<MST_Party>();
        }
    
        public int PartyTypeID { get; set; }
        public string PartyType { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<MST_Party> MST_Party { get; set; }
    }
}
