//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_FinYear
    {
        public SYS_FinYear()
        {
            this.ACC_Expense = new HashSet<ACC_Expense>();
            this.ACC_ExpenseHistory = new HashSet<ACC_ExpenseHistory>();
            this.DIA_Jangad = new HashSet<DIA_Jangad>();
            this.DIA_JangadHistory = new HashSet<DIA_JangadHistory>();
            this.EMP_Employee = new HashSet<EMP_Employee>();
            this.INV_Invoice = new HashSet<INV_Invoice>();
            this.INV_InvoiceHistory = new HashSet<INV_InvoiceHistory>();
            this.INV_ItemPrice = new HashSet<INV_ItemPrice>();
            this.INV_PurchaseOrder = new HashSet<INV_PurchaseOrder>();
            this.INV_PurchaseOrderHistory = new HashSet<INV_PurchaseOrderHistory>();
            this.INV_StockHistory = new HashSet<INV_StockHistory>();
        }
    
        public int FinYearID { get; set; }
        public string FinYear { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modifed { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<ACC_Expense> ACC_Expense { get; set; }
        public virtual ICollection<ACC_ExpenseHistory> ACC_ExpenseHistory { get; set; }
        public virtual ICollection<DIA_Jangad> DIA_Jangad { get; set; }
        public virtual ICollection<DIA_JangadHistory> DIA_JangadHistory { get; set; }
        public virtual ICollection<EMP_Employee> EMP_Employee { get; set; }
        public virtual ICollection<INV_Invoice> INV_Invoice { get; set; }
        public virtual ICollection<INV_InvoiceHistory> INV_InvoiceHistory { get; set; }
        public virtual ICollection<INV_ItemPrice> INV_ItemPrice { get; set; }
        public virtual ICollection<INV_PurchaseOrder> INV_PurchaseOrder { get; set; }
        public virtual ICollection<INV_PurchaseOrderHistory> INV_PurchaseOrderHistory { get; set; }
        public virtual ICollection<INV_StockHistory> INV_StockHistory { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
