//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Company
    {
        public SYS_Company()
        {
            this.DIA_Cassett = new HashSet<DIA_Cassett>();
            this.DIA_Jangad = new HashSet<DIA_Jangad>();
            this.DIA_JangadHistory = new HashSet<DIA_JangadHistory>();
            this.DIA_Machine = new HashSet<DIA_Machine>();
            this.DIA_MachineMaintenance = new HashSet<DIA_MachineMaintenance>();
            this.EMP_Employee = new HashSet<EMP_Employee>();
            this.INV_Invoice = new HashSet<INV_Invoice>();
            this.INV_InvoiceHistory = new HashSet<INV_InvoiceHistory>();
            this.INV_Item = new HashSet<INV_Item>();
            this.INV_PurchaseOrder = new HashSet<INV_PurchaseOrder>();
            this.INV_PurchaseOrderHistory = new HashSet<INV_PurchaseOrderHistory>();
            this.MST_Party = new HashSet<MST_Party>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string LogoPath { get; set; }
        public string Address { get; set; }
        public int CityID { get; set; }
        public string Phone { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
        public string PanNo { get; set; }
        public string TanNo { get; set; }
        public string GSTIN { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<DIA_Cassett> DIA_Cassett { get; set; }
        public virtual ICollection<DIA_Jangad> DIA_Jangad { get; set; }
        public virtual ICollection<DIA_JangadHistory> DIA_JangadHistory { get; set; }
        public virtual ICollection<DIA_Machine> DIA_Machine { get; set; }
        public virtual ICollection<DIA_MachineMaintenance> DIA_MachineMaintenance { get; set; }
        public virtual ICollection<EMP_Employee> EMP_Employee { get; set; }
        public virtual ICollection<INV_Invoice> INV_Invoice { get; set; }
        public virtual ICollection<INV_InvoiceHistory> INV_InvoiceHistory { get; set; }
        public virtual ICollection<INV_Item> INV_Item { get; set; }
        public virtual ICollection<INV_PurchaseOrder> INV_PurchaseOrder { get; set; }
        public virtual ICollection<INV_PurchaseOrderHistory> INV_PurchaseOrderHistory { get; set; }
        public virtual LOC_City LOC_City { get; set; }
        public virtual ICollection<MST_Party> MST_Party { get; set; }
        public virtual SEC_User SEC_User { get; set; }
    }
}
