//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnjaliMIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PolishingStage
    {
        public SYS_PolishingStage()
        {
            this.DIA_JangadItem = new HashSet<DIA_JangadItem>();
        }
    
        public int PolishingStageID { get; set; }
        public string SatgeName { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<DIA_JangadItem> DIA_JangadItem { get; set; }
    }
}
